#!/usr/bin/env python3
"""
Shared crypto for the attendance system — keeps card numbers out of plain text.

Design (must match the firmware's mbedTLS code byte-for-byte):
  master key K  : 32 random bytes, stored hex in secret.key (KEEP PRIVATE)
  subkeys       : kmac = SHA256("MAC|" + K),  kenc = SHA256("ENC|" + K)
  token(id)     : HMAC-SHA256(kmac, id_ascii)[:16]  -> 32 hex chars   (one-way, deterministic)
  encrypt(name) : AES-256-CBC(kenc, iv) with PKCS7; stored as hex(iv[16] + ciphertext)

The card number (a short decimal like 0984257796) is NEVER written to disk — only
its keyed token. Names are stored only as ciphertext. Without secret.key, a lost
roster.csv / attendance.csv / SD card is unreadable, and the low-entropy card IDs
cannot be brute-forced (the HMAC key is secret).

Requires:  pip install cryptography
"""
import os, hmac, hashlib, binascii
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

_HERE = os.path.dirname(os.path.abspath(__file__))
KEY_PATH_DEFAULT = os.path.join(_HERE, "secret.key")


def load_or_create_key(path=KEY_PATH_DEFAULT):
    """Return the 32-byte master key, creating secret.key on first use."""
    if os.path.exists(path):
        K = binascii.unhexlify(open(path).read().strip())
        if len(K) != 32:
            raise ValueError("secret.key must be 64 hex characters (32 bytes)")
        return K
    K = os.urandom(32)
    with open(path, "w") as f:
        f.write(K.hex())
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return K


def subkeys(K):
    kmac = hashlib.sha256(b"MAC|" + K).digest()
    kenc = hashlib.sha256(b"ENC|" + K).digest()
    return kmac, kenc


def token(K, id_str):
    """Keyed one-way token for a card id string (e.g. '0984257796')."""
    kmac, _ = subkeys(K)
    return hmac.new(kmac, id_str.encode("ascii"), hashlib.sha256).digest()[:16].hex()


def _pkcs7(b, bs=16):
    p = bs - (len(b) % bs)
    return b + bytes([p]) * p


def _unpkcs7(b):
    p = b[-1]
    if p < 1 or p > 16 or b[-p:] != bytes([p]) * p:
        raise ValueError("bad padding")
    return b[:-p]


def encrypt_name(K, name):
    _, kenc = subkeys(K)
    iv = os.urandom(16)
    enc = Cipher(algorithms.AES(kenc), modes.CBC(iv)).encryptor()
    ct = enc.update(_pkcs7(name.encode("utf-8"))) + enc.finalize()
    return (iv + ct).hex()


def decrypt_name(K, hexstr):
    _, kenc = subkeys(K)
    raw = binascii.unhexlify(hexstr)
    iv, ct = raw[:16], raw[16:]
    dec = Cipher(algorithms.AES(kenc), modes.CBC(iv)).decryptor()
    return _unpkcs7(dec.update(ct) + dec.finalize()).decode("utf-8")


def firmware_key_snippet(K):
    """secret_key.h contents — #included by the sketch, never pasted by hand."""
    arr = ", ".join("0x%02x" % b for b in K)
    return ("#pragma once\n"
            "// secret_key.h — generated by attendance_crypto.py. KEEP PRIVATE.\n"
            "// Do NOT commit this or copy it onto the SD card. Listed in .gitignore.\n"
            "static const uint8_t SECRET_KEY[32] = { " + arr + " };\n")


if __name__ == "__main__":
    # self-test + emit the firmware key header
    K = load_or_create_key()
    tid = "0984257796"
    print("token(%s) = %s" % (tid, token(K, tid)))
    h = encrypt_name(K, "Michael Hilton")
    print("enc len   =", len(h), "hex chars")
    print("roundtrip =", decrypt_name(K, h))
    out_path = os.path.join(_HERE, "..", "firmware", "attendance_reader_PN532", "secret_key.h")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w").write(firmware_key_snippet(K))
    print("wrote %s (the sketch #includes it automatically — nothing to paste)" % out_path)
